stages:
  prepare:
    cmd: python -m src.main prepare
    deps:
      - src/main.py
      - src/data_loader.py
      - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    params:
      - config/params.yaml:
        - data_split.test_size
        - data_split.random_state
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python -m src.main train
    deps:
      - src/main.py
      - src/model_trainer.py
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - config/params.yaml:
        - model.name
        - data_split.random_state
    outs:
      - models/model.pkl
