stages:
  prepare:
    cmd: python src/data_loader.py
    deps:
      - src/data_loader.py
      - data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
    params:
      # Se especifica la ruta del archivo antes de los nombres de los parámetros
      - config/params.yaml:
        - test_size
        - random_state
     outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/model_trainer.py
    deps:
      - src/model_trainer.py
      - data/processed/model_trainer.csv
    params:
      - config/params.yaml:
        - train.estimator
        - train.hyperparameters
    outs:
      - models/model.pkl
